global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'identity-service'
    static_configs:
      - targets: ['identity-service:8080']

  - job_name: 'property-service'
    static_configs:
      - targets: ['property-service:8080']

  - job_name: 'ingestion-service'
    static_configs:
      - targets: ['ingestion-service:8080']

  - job_name: 'alert-service'
    static_configs:
      - targets: ['alert-service:8080']